DTSPO-18501 - add vm-bootstrap module and required vars
hmcts/dynatrace-activegate pull request #26
Opened 2024-09-05 16:15 UTC by louisehuyton

### Jira link
DTSPO-18501

### Change description

### Testing done

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-09-09 11:31 UTC, hmcts-platform-operations commented
## Plan Result (nonprod_dynatrace_activegate)




<pre><code>Only Outputs will be changed.</code></pre>





<details><summary>Change Result (Click me)</summary>

```hcl
Changes to Outputs:
  + vm_result = [
      + {
          + xdr_tags = ""
        },
    ]

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":26,"Program":"tfcmt","SHA1":"","Target":"nonprod_dynatrace_activegate","Vars":{}} -->

2024-09-09 11:33 UTC, hmcts-platform-operations commented
## Plan Result (prod_dynatrace_activegate)




<pre><code>Only Outputs will be changed.</code></pre>





<details><summary>Change Result (Click me)</summary>

```hcl
Changes to Outputs:
  + vm_result = [
      + {
          + xdr_tags = ""
        },
    ]

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":26,"Program":"tfcmt","SHA1":"","Target":"prod_dynatrace_activegate","Vars":{}} -->

2024-09-09 14:07 UTC, endakelly commented
I'm assuming these aren't already in Splunk - maybe check with Narinder. Might need to watch for messages from SecOps if they query why there are some new VMs suddenly appearing in Splunk. Don't think it should be an issue though

2024-09-09 14:07 UTC, endakelly approved these changes

2024-09-09 14:19 UTC, cpareek requested changes
we will have to pass `run_command_sa_key`

2024-09-10 09:15 UTC, cpareek approved these changes

2024-09-10 11:52 UTC, merged